-- Skema Database PRESISI

-- 1. Tabel Kelas
CREATE TABLE IF NOT EXISTS classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel User (Siswa, Guru, Admin)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role TEXT NOT NULL CHECK (role IN ('student', 'teacher', 'admin')),
    identifier TEXT UNIQUE NOT NULL, -- NIS untuk siswa, NIP untuk guru, 'admin' untuk admin
    name TEXT NOT NULL,
    password TEXT NOT NULL,
    class TEXT REFERENCES classes(name) ON UPDATE CASCADE, -- Hanya untuk siswa
    subject TEXT, -- Hanya untuk guru
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel Ujian
CREATE TABLE IF NOT EXISTS exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    class TEXT REFERENCES classes(name) ON UPDATE CASCADE,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'finished')),
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabel Pertanyaan
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT REFERENCES exams(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('multiple_choice', 'essay')),
    question_text TEXT NOT NULL,
    option_a TEXT,
    option_b TEXT,
    option_c TEXT,
    option_d TEXT,
    option_e TEXT,
    correct_answer TEXT, -- A, B, C, atau D
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabel Pengumpulan (Submissions)
CREATE TABLE IF NOT EXISTS submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    exam_id BIGINT REFERENCES exams(id) ON DELETE CASCADE,
    score FLOAT DEFAULT 0,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabel Jawaban Detail
CREATE TABLE IF NOT EXISTS answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT REFERENCES submissions(id) ON DELETE CASCADE,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
    answer_text TEXT,
    score FLOAT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Tabel Settings
CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tambahkan index untuk performa
CREATE INDEX IF NOT EXISTS idx_users_identifier ON users(identifier);
CREATE INDEX IF NOT EXISTS idx_exams_teacher ON exams(teacher_id);
CREATE INDEX IF NOT EXISTS idx_questions_exam ON questions(exam_id);
CREATE INDEX IF NOT EXISTS idx_submissions_student ON submissions(student_id);
CREATE INDEX IF NOT EXISTS idx_submissions_exam ON submissions(exam_id);
CREATE INDEX IF NOT EXISTS idx_answers_submission ON answers(submission_id);

-- Matikan RLS untuk kemudahan pengembangan (karena kita menggunakan Service Role Key di server)
ALTER TABLE classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE exams DISABLE ROW LEVEL SECURITY;
ALTER TABLE questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE answers DISABLE ROW LEVEL SECURITY;

-- Migration: Add status columns to exams if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'exams' AND column_name = 'status') THEN
        ALTER TABLE exams ADD COLUMN status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'finished'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'exams' AND column_name = 'started_at') THEN
        ALTER TABLE exams ADD COLUMN started_at TIMESTAMPTZ;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'exams' AND column_name = 'ended_at') THEN
        ALTER TABLE exams ADD COLUMN ended_at TIMESTAMPTZ;
    END IF;
END $$;
